"""
Structured category_mappings for public report rendering (Milestone 2.7.1).
JSON retains full numerics; this block drives narrative, qualitative markdown/HTML.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Set
from urllib.parse import urlparse

from verityngn.models.report import Claim, EvidenceSource, map_probabilities_to_verification_result

INDEPENDENT_RESEARCH_DISCLAIMER = (
    "This assessment is independent editorial research by HotChili Analytics, LLC. "
    "Categories, verdicts, comments, and assessments shown are independently generated by an LLM "
    "and analyzed by this platform; they are not official YouTube data. "
    "They are not provided, endorsed, or calculated by YouTube or Google."
)

# Visible at top of reports (YouTube API ToS III.E.4.h — must not read as official YouTube data).
LLM_PLATFORM_VISIBLE_NOTICE = (
    "Categories, verdicts, comments, and assessments on this page are independently generated "
    "by an LLM and analyzed by HotChili Analytics, LLC (VerityIndex). They are not official YouTube data "
    "and are not provided, endorsed, or calculated by YouTube or Google."
)

VERDICT_BUCKET_LABELS: List[str] = [
    "Highly Likely True",
    "Likely True",
    "Leaning True",
    "Uncertain",
    "Unverifiable",
    "Leaning False",
    "Likely False",
    "Highly Likely False",
]

VERDICT_KEY_TO_LABEL: Dict[str, str] = {
    "HIGHLY_LIKELY_TRUE": "Highly Likely True",
    "LIKELY_TRUE": "Likely True",
    "LEANING_TRUE": "Leaning True",
    "UNCERTAIN": "Uncertain",
    "UNVERIFIABLE": "Unverifiable",
    "LEANING_FALSE": "Leaning False",
    "LIKELY_FALSE": "Likely False",
    "HIGHLY_LIKELY_FALSE": "Highly Likely False",
}


def _get_domain(url: str) -> str:
    try:
        domain = urlparse(url).netloc
        return domain.replace("www.", "").replace("m.", "").split(":")[0]
    except Exception:
        return ""


def map_source_type_category(source_type: Optional[str], url: Optional[str]) -> str:
    """Map raw source type or URL to standardized evidence category labels."""
    source_type_lower = (source_type or "").lower()
    domain = _get_domain(url or "")

    if "academic" in source_type_lower or ".edu" in domain:
        return "Academic Research"
    if "government" in source_type_lower or any(
        ending in domain for ending in [".gov", ".mil", "whitehouse.gov", "cdc.gov", "nih.gov", "fda.gov"]
    ):
        return "Government Publications"
    if "journal" in source_type_lower or any(
        kw in domain
        for kw in [
            "ncbi.nlm.nih",
            "pubmed",
            "nejm.",
            "jamanetwork.",
            "thelancet.",
            "nature.com",
            "science.org",
            "pnas.org",
        ]
    ):
        return "Scientific Journals"
    if "expert" in source_type_lower:
        return "Expert Opinions"
    if "fact-check" in source_type_lower or any(
        kw in domain
        for kw in [
            "factcheck.org",
            "politifact.",
            "snopes.",
            "reuters.com/fact-check",
            "apnews.com/ap-fact-check",
            "factcheck.afp.com",
        ]
    ):
        return "Fact-checking Organizations"
    if "news" in source_type_lower or any(
        kw in domain for kw in ["reuters.com", "apnews.com", "bbc.", "nytimes.", "wsj.", "cnn."]
    ):
        return "News Articles"
    return "Web Pages"


def _claim_internal_verdict_key(claim: Claim) -> str:
    """Match markdown_generator pre-process: honor UNVERIFIABLE, else map probabilities."""
    stored_result = ""
    if isinstance(claim.verification_result, dict):
        stored_result = (claim.verification_result.get("result", "") or "").upper()
    elif isinstance(claim.verification_result, str):
        stored_result = claim.verification_result.upper()

    if stored_result == "UNVERIFIABLE":
        return "UNVERIFIABLE"
    if stored_result in VERDICT_KEY_TO_LABEL:
        return stored_result

    if isinstance(claim.verification_result, dict):
        prob_dist = claim.verification_result.get("probability_distribution")
        if isinstance(prob_dist, dict):
            v = map_probabilities_to_verification_result(prob_dist)
            if v == "UNABLE_DETERMINE":
                return "UNCERTAIN"
            return v
        if stored_result:
            return stored_result if stored_result != "UNABLE_DETERMINE" else "UNCERTAIN"

    if isinstance(claim.verification_result, str):
        v = claim.verification_result.upper()
        if v == "UNABLE_DETERMINE":
            return "UNCERTAIN"
        if v in VERDICT_KEY_TO_LABEL:
            return v
        return v if v else "UNCERTAIN"

    return "UNCERTAIN"


def _verdict_counts(claims: List[Claim]) -> Dict[str, int]:
    keys = list(VERDICT_KEY_TO_LABEL.keys())
    counts = {k: 0 for k in keys}
    for c in claims:
        vk = _claim_internal_verdict_key(c)
        if vk in counts:
            counts[vk] = counts.get(vk, 0) + 1
    return counts


def compute_overall_verdict_label(claims: List[Claim]) -> str:
    """Same qualitative headline as legacy markdown (no counts in output)."""
    total = len(claims)
    if total == 0:
        return "Undetermined (No Claims)"
    vc = _verdict_counts(claims)
    false_count = vc.get("LIKELY_FALSE", 0) + vc.get("HIGHLY_LIKELY_FALSE", 0)
    true_count = vc.get("LIKELY_TRUE", 0) + vc.get("HIGHLY_LIKELY_TRUE", 0)
    if false_count / total >= 0.6:
        return "Highly Likely False"
    if false_count > true_count:
        return "Likely False"
    if true_count / total >= 0.6:
        return "Highly Likely True"
    if true_count >= false_count:
        return "Likely True"
    return "Mixed/Uncertain"


def _qualitative_evidence_quality(claims: List[Claim], evidence_sources: List[EvidenceSource]) -> str:
    """Strong | Mixed | Limited from share of higher-trust categories among collected sources."""
    categories: List[str] = []
    for e in evidence_sources or []:
        url = getattr(e, "url", None) or ""
        st = getattr(e, "source_type", None) or ""
        if url or st:
            categories.append(map_source_type_category(st, url))

    for c in claims or []:
        sources: List[Any] = []
        if isinstance(c.verification_result, dict):
            sources = c.verification_result.get("sources") or []
        for item in sources:
            url = None
            st = None
            if isinstance(item, dict):
                url = item.get("url")
                st = item.get("source_type")
            else:
                url = getattr(item, "url", None)
                st = getattr(item, "source_type", None)
            if url or st:
                categories.append(map_source_type_category(st, url))

    if not categories:
        return "Limited"

    high_trust = {
        "Academic Research",
        "Scientific Journals",
        "Government Publications",
        "Fact-checking Organizations",
    }
    n_high = sum(1 for x in categories if x in high_trust)
    ratio = n_high / len(categories)
    if ratio > 0.55:
        return "Strong"
    if ratio > 0.25:
        return "Mixed"
    return "Limited"


def _narrative_verification_status(claims: List[Claim]) -> str:
    if not claims:
        return "No claims assessed"
    uncertain = 0
    for c in claims:
        if _claim_internal_verdict_key(c) in ("UNCERTAIN",):
            uncertain += 1
    if uncertain == 0:
        return "All claims assessed"
    if uncertain <= max(1, len(claims) // 4):
        return "Most claims assessed"
    return "Several claims remain indeterminate"


def _narrative_source_diversity(claims: List[Claim], evidence_sources: List[EvidenceSource]) -> str:
    cats: Set[str] = set()
    for e in evidence_sources or []:
        url = getattr(e, "url", None) or ""
        st = getattr(e, "source_type", None) or ""
        if url or st:
            cats.add(map_source_type_category(st, url))
    for c in claims or []:
        if isinstance(c.verification_result, dict):
            for item in c.verification_result.get("sources") or []:
                url = item.get("url") if isinstance(item, dict) else getattr(item, "url", None)
                st = item.get("source_type") if isinstance(item, dict) else getattr(item, "source_type", None)
                if url or st:
                    cats.add(map_source_type_category(st, url))
    n = len(cats)
    if n >= 4:
        return "Multiple categories"
    if n >= 2:
        return "Several categories"
    if n == 1:
        return "Single category"
    return "Limited source categories"


def _narrative_time_distribution(claims: List[Claim]) -> str:
    if not claims:
        return "Not applicable"
    ts = {c.timestamp for c in claims if c and c.timestamp}
    n = len(ts)
    if n >= max(3, len(claims) // 2):
        return "Across the video's runtime"
    if n <= 1:
        return "Concentrated in one segment"
    return "Concentrated in parts of the runtime"


def collect_evidence_categories_present(claims: List[Claim], evidence_sources: List[EvidenceSource]) -> List[str]:
    found: Set[str] = set()
    for e in evidence_sources or []:
        url = getattr(e, "url", None) or ""
        st = getattr(e, "source_type", None) or ""
        if url or st:
            found.add(map_source_type_category(st, url))
    for c in claims or []:
        if isinstance(c.verification_result, dict):
            for item in c.verification_result.get("sources") or []:
                if isinstance(item, dict):
                    url = item.get("url")
                    st = item.get("source_type")
                else:
                    url = getattr(item, "url", None)
                    st = getattr(item, "source_type", None)
                if url or st:
                    found.add(map_source_type_category(st, url))
    # Stable order: prefer plan example ordering, then rest alpha
    preferred = [
        "Academic Research",
        "Government Publications",
        "Scientific Journals",
        "Expert Opinions",
        "Fact-checking Organizations",
        "News Articles",
        "Web Pages",
    ]
    ordered = [x for x in preferred if x in found]
    rest = sorted(x for x in found if x not in preferred)
    return ordered + rest


def _craap_to_public_table(craap: Dict[str, Any]) -> Dict[str, Dict[str, str]]:
    out: Dict[str, Dict[str, str]] = {}
    if not craap:
        return out
    for criterion, analysis_data in craap.items():
        level = "Low"
        explanation = ""
        if isinstance(analysis_data, (list, tuple)) and len(analysis_data) == 2:
            level_obj, explanation = analysis_data
            level = str(level_obj.value if hasattr(level_obj, "value") else level_obj)
        elif isinstance(analysis_data, dict):
            level = str(analysis_data.get("level", "Low"))
            explanation = str(analysis_data.get("explanation", ""))
        out[str(criterion).lower()] = {"score": level, "explanation": explanation}
    return out


def _counter_intel_summary(
    youtube_counter_intelligence: List[Dict[str, Any]],
    press_release_counter_intelligence: List[Dict[str, Any]],
) -> str:
    parts: List[str] = []
    if youtube_counter_intelligence:
        parts.append(
            "Independent YouTube videos were analyzed as counter-intelligence and incorporated into the verdicts."
        )
    if press_release_counter_intelligence:
        parts.append(
            "Promotional or press-release style documents were reviewed separately and weighted cautiously "
            "relative to independent coverage."
        )
    if not parts:
        return "No separate counter-intelligence package was attached to this report."
    return " ".join(parts)


def _executive_paragraph(overall_label: str, claims: List[Claim]) -> str:
    """Single paragraph, count-free (disclaimer is shown under Section 2 per report template)."""
    if not claims:
        return "No claims were available to assess for this video."
    return (
        f"This editorial review examines statements from the video and weighs them against cited external sources. "
        f"The overall pattern is summarized as **{overall_label}**."
    )


def _overall_assessment_sentence(overall_label: str, claims: List[Claim]) -> str:
    if not claims:
        return "No claims were analyzed, so truthfulness could not be assessed."
    if overall_label == "Highly Likely False":
        status = "significant credibility issues, with a strong majority of claims assessed as false."
    elif overall_label == "Likely False":
        status = "credibility concerns, with more claims assessed as false than true."
    elif overall_label == "Highly Likely True":
        status = "generally reliable content, with a strong majority of claims assessed as true."
    elif overall_label == "Likely True":
        status = "mostly reliable content, with more claims assessed as true than false."
    elif overall_label == "Undetermined (No Claims)":
        return "No claims were analyzed, so truthfulness could not be assessed."
    else:
        status = (
            "mixed reliability, containing a blend of verifiable and questionable claims, requiring viewer caution."
        )
    return f"This video demonstrates {status}"


def build_category_mappings(
    claims: List[Claim],
    evidence_sources: List[EvidenceSource],
    craap_analysis: Dict[str, Any],
    youtube_counter_intelligence: Optional[List[Dict[str, Any]]] = None,
    press_release_counter_intelligence: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Build the category_mappings object stored alongside the full numeric JSON."""
    yt = youtube_counter_intelligence or []
    pr = press_release_counter_intelligence or []

    overall_label = compute_overall_verdict_label(claims)

    buckets: Dict[str, List[int]] = {label: [] for label in VERDICT_BUCKET_LABELS}
    for c in claims:
        vk = _claim_internal_verdict_key(c)
        label = VERDICT_KEY_TO_LABEL.get(vk, "Uncertain")
        buckets.setdefault(label, []).append(c.claim_id)

    narrative = {
        "executive_paragraph": _executive_paragraph(overall_label, claims),
        "overall_assessment_sentence": _overall_assessment_sentence(overall_label, claims),
        "evidence_quality": _qualitative_evidence_quality(claims, evidence_sources),
        "verification_status": _narrative_verification_status(claims),
        "source_diversity": _narrative_source_diversity(claims, evidence_sources),
        "time_distribution": _narrative_time_distribution(claims),
    }

    return {
        "schema_version": 1,
        "overall_verdict_label": overall_label,
        "independent_research_disclaimer": INDEPENDENT_RESEARCH_DISCLAIMER,
        "llm_platform_visible_notice": LLM_PLATFORM_VISIBLE_NOTICE,
        "narrative": narrative,
        "verdict_buckets": buckets,
        "evidence_categories_present": collect_evidence_categories_present(claims, evidence_sources),
        "counter_intelligence_summary": _counter_intel_summary(yt, pr),
        "craap_table": _craap_to_public_table(craap_analysis or {}),
    }


def claim_verdict_display_label(claim: Claim) -> str:
    """Public-facing verdict label for a single claim (matches bucket keys)."""
    vk = _claim_internal_verdict_key(claim)
    return VERDICT_KEY_TO_LABEL.get(vk, "Uncertain")


def ensure_category_mappings(report: Any) -> Dict[str, Any]:
    """Use report.category_mappings if present; otherwise rebuild (e.g. legacy JSON load)."""
    existing = getattr(report, "category_mappings", None)
    if isinstance(existing, dict) and existing.get("schema_version"):
        # Patch legacy stored mappings with V.2 LLM visibility fields without invalidating schema.
        patched = dict(existing)
        if not patched.get("llm_platform_visible_notice"):
            patched["llm_platform_visible_notice"] = LLM_PLATFORM_VISIBLE_NOTICE
        if "independently generated by an LLM" not in (patched.get("independent_research_disclaimer") or ""):
            patched["independent_research_disclaimer"] = INDEPENDENT_RESEARCH_DISCLAIMER
        return patched
    claims = getattr(report, "claims_breakdown", None) or []
    evidence = getattr(report, "evidence_summary", None) or []
    craap = getattr(report, "craap_analysis", None) or {}
    yt = getattr(report, "youtube_counter_intelligence", None) or []
    pr = getattr(report, "press_release_counter_intelligence", None) or []
    return build_category_mappings(claims, evidence, craap, yt, pr)
